/**
 * One-time post-signup Clippar Mount offer (feat/mount-upsell).
 *
 * Shown exactly once, right after a NEW account is created (routing decided
 * by lib/mountOffer.resolvePostAuthRoute — never for returning logins), then
 * marked seen on mount so it can never reappear. Always skippable: the X and
 * "Maybe later" both continue to the tabs, exactly where signup previously
 * landed.
 *
 * The kit is a PHYSICAL product (phone mount + Bluetooth clicker + portable
 * charger), so per App Review 3.1.3(e) it must NOT use in-app purchase — the
 * CTA links out to the website in Safari. Deliberately zero subscription /
 * Pro content on this screen so the external link is only ever attached to
 * the physical box.
 */
import { useEffect } from 'react';
import { View, Text, Pressable, Linking, ScrollView } from 'react-native';
import { router } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import Animated, { FadeIn, FadeInDown } from 'react-native-reanimated';
import {
  X,
  Check,
  Smartphone,
  Bluetooth,
  BatteryCharging,
} from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import { theme } from '@/constants/theme';
import { config } from '@/constants/config';
import { GradientBackground } from '@/components/ui/GradientBackground';
import { Button } from '@/components/ui/Button';
import { markMountOfferSeen } from '@/lib/mountOffer';

const BENEFITS = [
  'Record every shot without touching your phone',
  'Clip it to your bag or the buggy',
  'Tap the clicker, keep playing',
];

const KIT_ITEMS = [
  { Icon: Smartphone, label: 'Phone mount' },
  { Icon: Bluetooth, label: 'Bluetooth clicker' },
  { Icon: BatteryCharging, label: 'Portable charger' },
] as const;

export default function MountOfferScreen() {
  const insets = useSafeAreaInsets();

  // Mark seen the moment the screen appears — the offer is strictly
  // once-ever, even if the app is killed before the user picks an option.
  useEffect(() => {
    void markMountOfferSeen();
  }, []);

  // Typed-routes union is regenerated by the expo dev server; the tabs route
  // is cast until that runs once (same pattern as login.tsx).
  const continueToApp = () => router.replace('/(tabs)' as never);

  const handleGetMount = () => {
    Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
    // External Safari link — physical goods don't go through IAP (3.1.3(e)).
    Linking.openURL(config.shop.mountUrl).catch(() => {});
    // Land the user on the tabs so returning from Safari drops them straight
    // into the app, not back on this one-shot screen.
    continueToApp();
  };

  const handleSkip = () => {
    Haptics.selectionAsync();
    continueToApp();
  };

  return (
    <GradientBackground>
      <View
        style={{
          flex: 1,
          paddingTop: insets.top + 8,
          paddingBottom: insets.bottom + 12,
          paddingHorizontal: 24,
        }}
      >
        {/* Skip is never more than one tap away — top-right X mirrors the
            paywall's close affordance. */}
        <Pressable
          onPress={handleSkip}
          hitSlop={12}
          style={{
            alignSelf: 'flex-end',
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: theme.colors.surfaceElevated,
            alignItems: 'center',
            justifyContent: 'center',
          }}
        >
          <X size={20} color={theme.colors.textSecondary} />
        </Pressable>

        <ScrollView
          showsVerticalScrollIndicator={false}
          contentContainerStyle={{ flexGrow: 1 }}
        >
          <Animated.View entering={FadeIn.duration(350)}>
            {/* Hero */}
            <View style={{ alignItems: 'center', marginTop: 8, marginBottom: 24 }}>
              <Text
                style={{
                  ...theme.typography.h1,
                  color: theme.colors.textPrimary,
                  textAlign: 'center',
                }}
              >
                You're in.
              </Text>
              <Text
                style={{
                  ...theme.typography.h1,
                  color: theme.colors.primary,
                  textAlign: 'center',
                }}
              >
                Want to go hands-free?
              </Text>
              <Text
                style={{
                  ...theme.typography.body,
                  color: theme.colors.textSecondary,
                  textAlign: 'center',
                  marginTop: 12,
                }}
              >
                The Clippar Mount kit sets your phone up on the course and puts
                the record button on a clicker in your pocket.
              </Text>
            </View>

            {/* The kit — three physical pieces, one box. */}
            <View
              style={{
                borderRadius: theme.radius.lg,
                backgroundColor: theme.colors.surface,
                borderWidth: 1,
                borderColor: theme.colors.surfaceBorder,
                padding: 20,
                marginBottom: 24,
              }}
            >
              <View
                style={{
                  flexDirection: 'row',
                  justifyContent: 'space-between',
                  marginBottom: 16,
                }}
              >
                {KIT_ITEMS.map(({ Icon, label }) => (
                  <View key={label} style={{ alignItems: 'center', flex: 1, gap: 8 }}>
                    <View
                      style={{
                        width: 48,
                        height: 48,
                        borderRadius: 24,
                        backgroundColor: theme.colors.primaryMuted,
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}
                    >
                      <Icon size={22} color={theme.colors.primary} />
                    </View>
                    <Text
                      style={{
                        color: theme.colors.textSecondary,
                        fontSize: 12,
                        fontWeight: '600',
                        textAlign: 'center',
                      }}
                    >
                      {label}
                    </Text>
                  </View>
                ))}
              </View>
              <View
                style={{
                  flexDirection: 'row',
                  alignItems: 'baseline',
                  justifyContent: 'center',
                  gap: 6,
                }}
              >
                <Text
                  style={{
                    color: theme.colors.textPrimary,
                    fontSize: 28,
                    fontWeight: '900',
                  }}
                >
                  {config.shop.mountPriceLabel}
                </Text>
                <Text style={{ color: theme.colors.textSecondary, fontSize: 14 }}>
                  one-time · the whole kit
                </Text>
              </View>
            </View>

            {/* Benefits */}
            <View style={{ gap: 12, marginBottom: 24 }}>
              {BENEFITS.map((b, i) => (
                <Animated.View
                  key={b}
                  entering={FadeInDown.delay(150 + i * 80).duration(300)}
                  style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}
                >
                  <Check size={18} color={theme.colors.primary} />
                  <Text
                    style={{ color: theme.colors.textPrimary, fontSize: 15, flex: 1 }}
                  >
                    {b}
                  </Text>
                </Animated.View>
              ))}
            </View>
          </Animated.View>

          <View style={{ flex: 1 }} />

          <Button title="Get the Clippar Mount" onPress={handleGetMount} />
          <Button
            title="Maybe later"
            onPress={handleSkip}
            variant="ghost"
            style={{ marginTop: 10 }}
          />

          {/* Reassurance — the app is fully usable without the kit. */}
          <Text
            style={{
              color: theme.colors.textTertiary,
              fontSize: 12,
              textAlign: 'center',
              marginTop: 12,
            }}
          >
            No pressure — Clippar works great with just your phone, too.
          </Text>
        </ScrollView>
      </View>
    </GradientBackground>
  );
}
