/**
 * A SECOND synthetic clip, with deliberately different geometry from
 * `tracerV3Clip.ts`: 4K portrait at 30 fps rather than 1080p at 60.
 *
 * WHY IT EXISTS. Gate NEW-1 (`docs/tracer-v3/re-verify.md`) was found on this
 * geometry and CANNOT be reproduced on `tracerV3Clip.ts` — I checked rather than
 * assumed: every 8-, 10- and 12-frame variant of that fixture, against GPS
 * carries of 5-80 m, lands on `carry_inconsistent`, never on `carry_as_scale`.
 * The verdict that was the bug only fires when the PIXEL-ONLY carry sigma
 * exceeds 15 % of the pixel carry, and at 60 fps the same number of frames spans
 * half the arc, so the fit is tight enough that it never does. Half the frame
 * rate over the same frame count is a longer baseline in time but a much shorter
 * one in the part of the flight that pins depth — which is exactly the short,
 * loose track the phone actually produces (`minTrackEmit` is 3).
 *
 * So this is not "another fixture". It is the shape of clip on which a wrong GPS
 * distance could still be drawn confidently, and a fix tuned to the 1080p60
 * fixture passes that one for free. The numbers below are the gate agent's own:
 * 2160x3840, 30 fps, 9 deg of camera pitch, camera 1.62 m up, ball 3.2 m out and
 * 0.6 m right, 68 deg landscape field of view.
 *
 * Conventions are `lib/tracerFit.ts`'s, identical to the sibling fixture: the
 * flight is simulated from z0 = the ball radius, and world z is measured from
 * `start.z - BALL_RADIUS_M`.
 */
import { BALL_RADIUS_M, simulate } from '../../lib/tracerPhysics';
import { TracerCamera } from '../../lib/tracerCamera';
import {
  fPxFromLandscapeFov,
  type BallDetection,
  type TraceClipInput,
  type TracerDetectResultV3,
} from '../../lib/tracerV3';

export const WIDTH = 2160;
export const HEIGHT = 3840;
export const FPS = 30;
export const K_IMPACT = 50;
/** Fractional frame at which the ball leaves the club, inside [k/fps, (k+1)/fps]. */
export const T0_SEC = (K_IMPACT + 0.4) / FPS;
export const PITCH_DOWN_DEG = 9;
export const H_CAM_M = 1.62;
export const FOV_LANDSCAPE_DEG = 68;

export const F_PX = fPxFromLandscapeFov(FOV_LANDSCAPE_DEG, WIDTH, HEIGHT);

/** On the ground, 3.2 m in front of the camera and 0.6 m right. */
export const BALL_START = { x: 3.2, y: -0.6, z: BALL_RADIUS_M };

export function truthCamera(): TracerCamera {
  return new TracerCamera({
    fPx: F_PX,
    width: WIDTH,
    height: HEIGHT,
    pitchDownDeg: PITCH_DOWN_DEG,
    rollDeg: 0,
    hCamM: H_CAM_M,
    fPxIsPrior: true,
  });
}

export function addressCue(cam: TracerCamera): { x: number; y: number; r: number } {
  const axes = cam.sphereImageAxes(BALL_START);
  return { x: axes.centrePx.x, y: axes.centrePx.y, r: Math.sqrt(axes.aPx * axes.bPx) };
}

export interface ShortTrackOpts {
  v0?: number;
  thetaDeg?: number;
  phiDeg?: number;
  rpmBack?: number;
  frames?: number;
  conf?: number;
}

function flightOf(o: ShortTrackOpts) {
  return simulate({
    v0: o.v0 ?? 75,
    thetaDeg: o.thetaDeg ?? 13,
    phiDeg: o.phiDeg ?? 4,
    rpmBack: o.rpmBack ?? 2600,
    rpmSide: 0,
    z0: BALL_RADIUS_M,
  });
}

/** What the ball ACTUALLY did — the number every error below is measured against. */
export function truthSummary(o: ShortTrackOpts = {}) {
  return flightOf(o).summary;
}

/** Detections generated by projecting that real simulated flight. */
export function flightDetections(o: ShortTrackOpts = {}): BallDetection[] {
  const cam = truthCamera();
  const flight = flightOf(o);
  const n = o.frames ?? 8;
  const out: BallDetection[] = [];
  for (let i = 1; i <= n; i++) {
    const frame = K_IMPACT + i;
    const tau = frame / FPS - T0_SEC;
    const s = flight.at(tau);
    const world = {
      x: BALL_START.x + s.x,
      y: BALL_START.y + s.y,
      z: BALL_START.z - BALL_RADIUS_M + s.z,
    };
    const uv = cam.project([world])[0];
    const axes = cam.sphereImageAxes(world);
    out.push({
      frame,
      t: frame / FPS,
      x: uv.x,
      y: uv.y,
      r: Math.sqrt(axes.aPx * axes.bPx),
      conf: o.conf ?? 0.8,
    });
  }
  return out;
}

export function detectionResult(
  detections: BallDetection[],
  overrides: Partial<TracerDetectResultV3> = {}
): TracerDetectResultV3 {
  const cam = truthCamera();
  return {
    found: true,
    method: 'blob-kalman',
    fps: FPS,
    width: WIDTH,
    height: HEIGHT,
    impactFrameGiven: K_IMPACT,
    impactFrameUsed: K_IMPACT,
    launchFrame: K_IMPACT + 1,
    address: addressCue(cam),
    detections,
    notes: {},
    msPerFrame: 12,
    ...overrides,
  };
}

export function traceInput(overrides: Partial<TraceClipInput> = {}): TraceClipInput {
  return {
    detection: detectionResult(flightDetections()),
    pitchDownDeg: PITCH_DOWN_DEG,
    fPx: F_PX,
    fPxSource: 'fov-metadata',
    capture: { lens: '1x', zoom: 0 },
    shotType: 'swing',
    renderDurationSec: 6,
    detectToRenderOffsetSec: 0,
    ...overrides,
  };
}
