/**
 * A FIFTH synthetic clip: the flat, low, dropped-frame track that the fit gets
 * CONFIDENTLY and enormously wrong — FG-1's headline case
 * (`docs/tracer-v3/final-gate.md`).
 *
 * WHY IT EXISTS, and why the four siblings will not do. The other fixtures are
 * clean: every one of them recovers its own flight to within 5 %, which is what
 * makes them good controls and useless as a reproduction of FG-1. FG-1 is not
 * "the fit is noisy", it is "the fit converges on a completely different flight
 * and the pill states it to the nearest 10 metres". Three things produce that,
 * and no sibling has any of them:
 *
 *   1. a FLAT launch (8.8 deg) at modest speed, so the arc barely curves inside
 *      the window and depth is almost unconstrained;
 *   2. DROPPED FRAMES — the detector emits every second frame — so the track
 *      spans twice the time at half the density, which is what the gate's worst
 *      rows all had and what none of the other fixtures models at all;
 *   3. detections starting 3 frames after impact, so the launch itself is never
 *      seen.
 *
 * The result: a 65 m shot fitted at 281 m. **+329 %**, drawn at a 10 m rounding
 * step, with no GPS anywhere near it — which is FG-1's whole point, and why the
 * three previous rounds of carry-verdict fixes could never have reached it.
 *
 * All three of FG-1's tests fire here, and the flag says so:
 *   `too_uncertain_no_distance(sigma_v0=51%>=5%,rms=3.2px>2px@1080,sigma=111m>25%_of_281m)`
 *
 * THE GEOMETRY is the camera the gate's worst row sat on (1284x2778 at 60 fps,
 * 0.8 deg of pitch, camera 1.75 m up, 77 deg landscape FOV, ball 5.5 m out and
 * 0.9 m left), and the launch family it quoted. It is NOT a re-typing of that
 * row — the gate says plainly that its CSV rounds to 2 dp and that an
 * ill-conditioned clip is chaotic, so a re-typed row does not reproduce. This is
 * the same geometry FAMILY, generated here, with its own truth.
 *
 * Conventions are `lib/tracerFit.ts`'s, identical to all four siblings: the
 * flight is simulated from z0 = the ball radius, and world z is measured from
 * `start.z - BALL_RADIUS_M`.
 */
import { BALL_RADIUS_M, simulate } from '../../lib/tracerPhysics';
import { TracerCamera } from '../../lib/tracerCamera';
import {
  fPxFromLandscapeFov,
  type BallDetection,
  type TraceClipInput,
  type TracerDetectResultV3,
} from '../../lib/tracerV3';

export const WIDTH = 1284;
export const HEIGHT = 2778;
export const FPS = 60;
export const K_IMPACT = 40;
export const PITCH_DOWN_DEG = 0.8;
export const H_CAM_M = 1.75;
export const FOV_LANDSCAPE_DEG = 77;

export const F_PX = fPxFromLandscapeFov(FOV_LANDSCAPE_DEG, WIDTH, HEIGHT);

/** On the ground, 5.5 m in front of the camera and 0.9 m to the left. */
export const BALL_START = { x: 5.5, y: 0.9, z: BALL_RADIUS_M };

/** Impact half a frame after `K_IMPACT`. */
export const SUB_FRAME = 0.5;
export function t0Sec(fps = FPS): number {
  return (K_IMPACT + SUB_FRAME) / fps;
}

export function truthCamera(): TracerCamera {
  return new TracerCamera({
    fPx: F_PX,
    width: WIDTH,
    height: HEIGHT,
    pitchDownDeg: PITCH_DOWN_DEG,
    rollDeg: 0,
    hCamM: H_CAM_M,
    fPxIsPrior: true,
  });
}

export function addressCue(cam: TracerCamera): { x: number; y: number; r: number } {
  const axes = cam.sphereImageAxes(BALL_START);
  return { x: axes.centrePx.x, y: axes.centrePx.y, r: Math.sqrt(axes.aPx * axes.bPx) };
}

export interface DroppedFrameOpts {
  v0?: number;
  thetaDeg?: number;
  phiDeg?: number;
  rpmBack?: number;
  frames?: number;
  fps?: number;
  /** Frames between detections. 2 is the dropped-frame track this exists for. */
  stride?: number;
  /** Frames after `K_IMPACT` the first detection lands on. */
  start?: number;
  conf?: number;
}

function flightOf(o: DroppedFrameOpts) {
  return simulate({
    v0: o.v0 ?? 41.07,
    // Flat and slow: the two things that leave depth unconstrained.
    thetaDeg: o.thetaDeg ?? 8.81,
    phiDeg: o.phiDeg ?? 3.83,
    rpmBack: o.rpmBack ?? 1266,
    rpmSide: 0,
    z0: BALL_RADIUS_M,
  });
}

/** What the ball ACTUALLY did — the number every error is measured against. */
export function truthSummary(o: DroppedFrameOpts = {}) {
  return flightOf(o).summary;
}

/** Detections generated by projecting that real simulated flight. */
export function flightDetections(o: DroppedFrameOpts = {}): BallDetection[] {
  const cam = truthCamera();
  const flight = flightOf(o);
  const fps = o.fps ?? FPS;
  const t0 = t0Sec(fps);
  const n = o.frames ?? 12;
  const stride = o.stride ?? 2;
  const start = o.start ?? 3;
  const out: BallDetection[] = [];
  for (let i = 0; i < n; i++) {
    const frame = K_IMPACT + start + i * stride;
    const tau = frame / fps - t0;
    if (tau <= 0) continue;
    const s = flight.at(tau);
    const world = {
      x: BALL_START.x + s.x,
      y: BALL_START.y + s.y,
      z: BALL_START.z - BALL_RADIUS_M + s.z,
    };
    const uv = cam.project([world])[0];
    const axes = cam.sphereImageAxes(world);
    out.push({
      frame,
      t: frame / fps,
      x: uv.x,
      y: uv.y,
      r: Math.sqrt(axes.aPx * axes.bPx),
      conf: o.conf ?? 0.6,
    });
  }
  return out;
}

export function detectionResult(
  detections: BallDetection[],
  overrides: Partial<TracerDetectResultV3> = {}
): TracerDetectResultV3 {
  const cam = truthCamera();
  return {
    found: true,
    method: 'blob-kalman',
    fps: FPS,
    width: WIDTH,
    height: HEIGHT,
    impactFrameGiven: K_IMPACT,
    impactFrameUsed: K_IMPACT,
    // The detector saw it leave three frames late, which is the point.
    launchFrame: K_IMPACT + 3,
    address: addressCue(cam),
    detections,
    notes: {},
    msPerFrame: 11,
    ...overrides,
  };
}

export function traceInput(overrides: Partial<TraceClipInput> = {}): TraceClipInput {
  return {
    detection: detectionResult(flightDetections()),
    pitchDownDeg: PITCH_DOWN_DEG,
    fPx: F_PX,
    fPxSource: 'fov-metadata',
    capture: { lens: '1x', zoom: 0 },
    shotType: 'swing',
    renderDurationSec: 8,
    detectToRenderOffsetSec: 0,
    ...overrides,
  };
}
