/**
 * A SYNTHETIC tracer clip: a real simulated flight, projected through a real
 * camera, delivered in exactly the shape `detectShotV3` returns.
 *
 * Shared by tests/tracerV3.test.ts and tests/tracerV3Wiring.test.ts so the two
 * cannot disagree about what a valid clip looks like — a hand-drawn "parabola
 * in pixels" is NOT one, and the ladder correctly refuses it (`poor_fit`),
 * which is how this file came to exist.
 *
 * The conventions are `lib/tracerFit.ts`'s own: the flight is simulated from
 * z0 = the ball radius and world z is measured from `start.z - BALL_RADIUS_M`,
 * so a fixture the fit cannot recover is a real disagreement rather than a
 * fixture bug.
 */
import { BALL_RADIUS_M, simulate } from '../../lib/tracerPhysics';
import { TracerCamera } from '../../lib/tracerCamera';
import {
  fPxFromLandscapeFov,
  type BallDetection,
  type TraceClipInput,
  type TracerDetectResultV3,
} from '../../lib/tracerV3';

export const WIDTH = 1080;
export const HEIGHT = 1920;
export const FPS = 60;
export const K_IMPACT = 100;
/** Fractional frame at which the ball actually leaves the club. Must lie in
 *  [k/fps, (k+1)/fps] — the fit bounds t0 to exactly that interval. */
export const T0_SEC = (K_IMPACT + 0.4) / FPS;
export const PITCH_DOWN_DEG = 6;
export const H_CAM_M = 1.4;
export const FOV_LANDSCAPE_DEG = 62;

export const F_PX = fPxFromLandscapeFov(FOV_LANDSCAPE_DEG, WIDTH, HEIGHT);

export function truthCamera(): TracerCamera {
  return new TracerCamera({
    fPx: F_PX,
    width: WIDTH,
    height: HEIGHT,
    pitchDownDeg: PITCH_DOWN_DEG,
    rollDeg: 0,
    hCamM: H_CAM_M,
    fPxIsPrior: true,
  });
}

/** Ball at address: on the ground, 4 m in front of the camera, 0.3 m left. */
export const BALL_START = { x: 4.0, y: 0.3, z: BALL_RADIUS_M };

export function addressCue(cam: TracerCamera): { x: number; y: number; r: number } {
  const axes = cam.sphereImageAxes(BALL_START);
  // A blob detector measures the ELLIPSE, so the fixture reports what it would:
  // the ellipse centre, and the equivalent (geometric-mean) radius. aPx/bPx are
  // semi-axes, hence no factor of two here and one in the diameter downstream.
  return { x: axes.centrePx.x, y: axes.centrePx.y, r: Math.sqrt(axes.aPx * axes.bPx) };
}

export interface FlightFixtureOpts {
  v0?: number;
  thetaDeg?: number;
  phiDeg?: number;
  rpmBack?: number;
  frames?: number;
  conf?: number;
}

/** Detections generated by projecting a real simulated flight. */
export function flightDetections(opts: FlightFixtureOpts = {}): BallDetection[] {
  const cam = truthCamera();
  const flight = simulate({
    v0: opts.v0 ?? 62,
    thetaDeg: opts.thetaDeg ?? 13,
    phiDeg: opts.phiDeg ?? 4,
    rpmBack: opts.rpmBack ?? 3000,
    rpmSide: 0,
    z0: BALL_RADIUS_M,
  });
  const n = opts.frames ?? 12;
  const out: BallDetection[] = [];
  for (let i = 1; i <= n; i++) {
    const frame = K_IMPACT + i;
    const tau = frame / FPS - T0_SEC;
    const s = flight.at(tau);
    // Exactly `positionsAt`'s convention in lib/tracerFit.ts.
    const world = {
      x: BALL_START.x + s.x,
      y: BALL_START.y + s.y,
      z: BALL_START.z - BALL_RADIUS_M + s.z,
    };
    const uv = cam.project([world])[0];
    const axes = cam.sphereImageAxes(world);
    out.push({
      frame,
      t: frame / FPS,
      x: uv.x,
      y: uv.y,
      r: Math.sqrt(axes.aPx * axes.bPx),
      conf: opts.conf ?? 0.8,
    });
  }
  return out;
}

export function detectionResult(detections: BallDetection[], overrides: Partial<TracerDetectResultV3> = {}): TracerDetectResultV3 {
  const cam = truthCamera();
  return {
    found: true,
    method: 'blob-kalman',
    fps: FPS,
    width: WIDTH,
    height: HEIGHT,
    impactFrameGiven: K_IMPACT,
    impactFrameUsed: K_IMPACT,
    launchFrame: K_IMPACT + 1,
    address: addressCue(cam),
    detections,
    notes: {},
    msPerFrame: 12,
    ...overrides,
  };
}

export function traceInput(overrides: Partial<TraceClipInput> = {}): TraceClipInput {
  return {
    detection: detectionResult(flightDetections()),
    pitchDownDeg: PITCH_DOWN_DEG,
    fPx: F_PX,
    fPxSource: 'fov-metadata',
    // The optics F_PX above actually describes: the 1x wide lens at its native
    // framing. Supplied explicitly because omitting it is a REFUSAL, not a
    // default — see TraceClipInput.capture and REVIEW F3a. Override it to test
    // what a 0.5x or pinch-zoomed clip does.
    capture: { lens: '1x', zoom: 0 },
    shotType: 'swing',
    renderDurationSec: 6,
    detectToRenderOffsetSec: 0,
    ...overrides,
  };
}
