/**
 * A THIRD synthetic clip: the flat, short, moderately-loose track on which a GPS
 * carry the pixels disagree with used to reach a confident, GPS-backed number
 * through the `carry_tension` rung (GATE-1, `docs/tracer-v3/gate.md`).
 *
 * WHY IT EXISTS, and why neither sibling fixture will do. `carry_tension` is the
 * band `2 < |z| <= 4`, and the failure needs the pixel-only carry sigma to land
 * in a NARROW window: loose enough that it divides the ordinary z-score down
 * below the 4-sigma inconsistency bar, but still UNDER the 15 % `carry_as_scale`
 * threshold, so the as-scale rung — the one the previous round fixed — never
 * fires and never looks. The gate agent measured 14.13 % on the worst clip.
 *   - `tracerV3Clip.ts` (1080p60, 12 frames) is far too tight: it never reaches
 *     the band at all.
 *   - `tracerV3ShortTrack.ts` (4K30, 8 frames) is too LOOSE — 34-69 % — so it
 *     lands in `carry_as_scale` and is caught by the previous round's fix.
 * The band between them is where GATE-1 lived, and one of the tests in
 * `tests/tracerV3Refusals.test.ts` asserts that this fixture actually reaches
 * `carry_tension`, so a later "simplification" that merges the three fixtures
 * cannot silently delete the reproduction.
 *
 * WHAT PUTS IT THERE. A flat launch (10 deg) over few frames: depth is weakly
 * determined when the arc barely climbs, so the pixel-only carry is loose — but
 * not as loose as the 4K30 fixture, because a 60 fps clip's frames are closer
 * together in time and the fit is correspondingly better conditioned. Every
 * failing row in the gate agent's 9 072-clip sweep was at the flattest launch
 * angle it tested.
 *
 * The geometry is the gate agent's own, deliberately different from both
 * siblings: 1440x2560 at 60 fps (and 30 where a test wants it), 4.5 deg of
 * camera pitch, camera 1.48 m up, ball 2.4 m out and 1.1 m to the left,
 * 73 deg landscape field of view.
 *
 * Conventions are `lib/tracerFit.ts`'s, identical to both siblings: the flight
 * is simulated from z0 = the ball radius, and world z is measured from
 * `start.z - BALL_RADIUS_M`.
 */
import { BALL_RADIUS_M, simulate } from '../../lib/tracerPhysics';
import { TracerCamera } from '../../lib/tracerCamera';
import {
  fPxFromLandscapeFov,
  type BallDetection,
  type TraceClipInput,
  type TracerDetectResultV3,
} from '../../lib/tracerV3';

export const WIDTH = 1440;
export const HEIGHT = 2560;
/** The band was found at 60 fps; `flightDetections` takes an fps so a test can
 *  ask for 30 and get the same geometry at half the sampling rate. */
export const FPS = 60;
export const K_IMPACT = 40;
export const PITCH_DOWN_DEG = 4.5;
export const H_CAM_M = 1.48;
export const FOV_LANDSCAPE_DEG = 73;

export const F_PX = fPxFromLandscapeFov(FOV_LANDSCAPE_DEG, WIDTH, HEIGHT);

/** On the ground, 2.4 m in front of the camera and 1.1 m to the left. */
export const BALL_START = { x: 2.4, y: 1.1, z: BALL_RADIUS_M };

/** Fractional frame at which the ball leaves the club, inside [k/fps, (k+1)/fps]. */
export function t0Sec(fps: number): number {
  return (K_IMPACT + 0.4) / fps;
}

export function truthCamera(): TracerCamera {
  return new TracerCamera({
    fPx: F_PX,
    width: WIDTH,
    height: HEIGHT,
    pitchDownDeg: PITCH_DOWN_DEG,
    rollDeg: 0,
    hCamM: H_CAM_M,
    fPxIsPrior: true,
  });
}

export function addressCue(cam: TracerCamera): { x: number; y: number; r: number } {
  const axes = cam.sphereImageAxes(BALL_START);
  return { x: axes.centrePx.x, y: axes.centrePx.y, r: Math.sqrt(axes.aPx * axes.bPx) };
}

export interface FlatTensionOpts {
  v0?: number;
  thetaDeg?: number;
  phiDeg?: number;
  rpmBack?: number;
  frames?: number;
  fps?: number;
  conf?: number;
}

function flightOf(o: FlatTensionOpts) {
  return simulate({
    v0: o.v0 ?? 55,
    // The flat launch is the whole point — see the header.
    thetaDeg: o.thetaDeg ?? 10,
    phiDeg: o.phiDeg ?? 1,
    rpmBack: o.rpmBack ?? 3400,
    rpmSide: 0,
    z0: BALL_RADIUS_M,
  });
}

/** What the ball ACTUALLY did — the number every error below is measured against. */
export function truthSummary(o: FlatTensionOpts = {}) {
  return flightOf(o).summary;
}

/** Detections generated by projecting that real simulated flight. */
export function flightDetections(o: FlatTensionOpts = {}): BallDetection[] {
  const cam = truthCamera();
  const flight = flightOf(o);
  const fps = o.fps ?? FPS;
  const t0 = t0Sec(fps);
  const n = o.frames ?? 5;
  const out: BallDetection[] = [];
  for (let i = 1; i <= n; i++) {
    const frame = K_IMPACT + i;
    const tau = frame / fps - t0;
    const s = flight.at(tau);
    const world = {
      x: BALL_START.x + s.x,
      y: BALL_START.y + s.y,
      z: BALL_START.z - BALL_RADIUS_M + s.z,
    };
    const uv = cam.project([world])[0];
    const axes = cam.sphereImageAxes(world);
    out.push({
      frame,
      t: frame / fps,
      x: uv.x,
      y: uv.y,
      r: Math.sqrt(axes.aPx * axes.bPx),
      conf: o.conf ?? 0.8,
    });
  }
  return out;
}

export function detectionResult(
  detections: BallDetection[],
  overrides: Partial<TracerDetectResultV3> = {}
): TracerDetectResultV3 {
  const cam = truthCamera();
  return {
    found: true,
    method: 'blob-kalman',
    fps: FPS,
    width: WIDTH,
    height: HEIGHT,
    impactFrameGiven: K_IMPACT,
    impactFrameUsed: K_IMPACT,
    launchFrame: K_IMPACT + 1,
    address: addressCue(cam),
    detections,
    notes: {},
    msPerFrame: 11,
    ...overrides,
  };
}

export function traceInput(overrides: Partial<TraceClipInput> = {}): TraceClipInput {
  return {
    detection: detectionResult(flightDetections()),
    pitchDownDeg: PITCH_DOWN_DEG,
    fPx: F_PX,
    fPxSource: 'fov-metadata',
    capture: { lens: '1x', zoom: 0 },
    shotType: 'swing',
    renderDurationSec: 6,
    detectToRenderOffsetSec: 0,
    ...overrides,
  };
}
